services:
  web:
    build: .
    ports:
      - "${APP_PORT}:8000"
    environment:
      - DJANGO_SECRET_KEY=$
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DATABASE_URL

  # redis:
  #   image: redis:alpine
