# Generated by Django 6.0.3 on 2026-04-01 22:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="TaxRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_code", models.CharField(db_index=True, max_length=2)),
                ("id_type", models.CharField(max_length=20)),
                (
                    "value",
                    models.CharField(
                        db_index=True,
                        help_text="Store raw alphanumeric values only.",
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tax_ids", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("country_code", "id_type", "value")},
            },
        ),
    ]
