# Generated by Django 6.0.3 on 2026-04-02 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_occupation_taxregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_type",
                    models.CharField(
                        choices=[("house", "House"), ("apt", "Apartment"), ("off", "Office")], max_length=20
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=10)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                (
                    "line_2",
                    models.CharField(
                        blank=True, help_text="Apartment, suite, unit, floor, etc.", max_length=100, null=True
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("complement", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
