# Generated by Django 6.0.3 on 2026-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_address"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)), fields=("user",), name="unique_default_address_per_user"
            ),
        ),
    ]
